package com.arun.springwithdynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.arun.springwithdynamodb.bootstrap.LocalDateTimeConverter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "Message")
@Getter
@Setter
public class Message {
    //partition key
    @DynamoDBHashKey
    private String itemId;

    //sort key
    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    @JsonIgnore
    private String messageId;

    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime dateTime;

    //GSI partition
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "UserId-index")
    private String userId;
    //GSI sort key and LSI
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "UserId-index", localSecondaryIndexName = "Rating-index")
    private int rating;
}
