package com.arun.springwithdynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

@DynamoDBTable(tableName = "User")
@Getter
@Setter
public class User {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String age;
    @DynamoDBAttribute
    private String address;
}
